src/modules/Catalog/Phones/Phones.tsx
src/modules/Shared/Card/Card.module.scss
src/modules/Shared/Card/Card.tsx

fixed text color

---

src/modules/ErrorPage/ErrorPage.module.scss
src/modules/ErrorPage/ErrorPage.tsx

- Add error text
- Add button 'Back home'

[Task: 86bybjqe5] Add Not Found page

---

src/modules/Shared/Loader/Loader.module.scss
src/modules/Shared/Loader/Loader.tsx
src/modules/Shared/Loader/index.ts

- Loader component added to the Shared folder

Loader component added

---

src/MainContext/MainContext.tsx
src/MainContext/MainContext.types.ts
src/MainContext/MainContextCart.ts
src/modules/Cart/Cart.module.scss
src/modules/Cart/Cart.tsx

-Added local storage 
-Added logic for removing items
-Added logic for quantity buttons
https://www.loom.com/share/5719480b93af4774915fda87981f67dd?sid=1fd36676-4a8e-4399-8ad3-efe37bfd5c00

added logic for removing item and quantity buttons logic

---

src/MainContext/MainContext.tsx
src/MainContext/MainContext.types.ts
src/modules/Cart/Cart.tsx
src/modules/Header/ShoppingTools/ShoppingTools.tsx

-Added calculation for total price
-Added calculation for total quantity

cart calculation added

---

src/modules/ProductDetails/ProductDetails.tsx
src/modules/ProductDetails/ProductInfo/ProductInfo.module.scss

- Added recommended slider on the product page with hardcoded data

recommended slider added

---

src/App.tsx
src/helpers/findProductById.ts
src/helpers/getProductIdFromUrl.ts
src/modules/ProductDetails/ProductDetails.tsx
src/modules/ProductDetails/ProductInfo/ProductInfo.tsx

-Added a function for finding the product 
-Loaded data from JSON
-Added product name to breadcrumbs
-When you enter the product page it scrolls to the slider

added loading info about products from JSON

---

src/modules/ProductDetails/ProductDetails.module.scss
src/modules/ProductDetails/ProductDetails.tsx
src/modules/ProductDetails/VariantsSection/VariantsSection.module.scss
src/modules/ProductDetails/VariantsSection/VariantsSection.tsx
src/modules/ProductDetails/VariantsSection/index.ts

- Ads selected product photos slider in variants section

[Task: 86bybjq6n] Add selecting photos block

---

src/modules/Cart/Cart.tsx
src/modules/Cart/SuccessModal/SuccessModal.module.scss
src/modules/Cart/SuccessModal/SuccessModal.tsx
src/modules/Cart/SuccessModal/index.ts
src/modules/Shared/Button/Button.tsx
src/modules/Shared/Title/Title.module.scss

-Add modal window
-Add useState to Cart
-[https://loom.com/share/0f6e0adb01b34315ae227f70b75ac3a4]

[Task: 86bybjq9p] add modal window

---

src/modules/Header/Search/Search.module.scss
src/modules/Header/Search/SearchResults/SearchResults.module.scss

-Added scroll for search results

scroll added for search results 

---

src/App.tsx

-Added scroll to top after route change

top scroll added

---

src/helpers/getProductByItemId.ts
src/modules/ProductDetails/ProductDetails.tsx
src/modules/ProductDetails/VariantsSection/CapacityRadioButton/CapacityRadioButton.module.scss
src/modules/ProductDetails/VariantsSection/CapacityRadioButton/CapacityRadioButton.tsx
src/modules/ProductDetails/VariantsSection/CapacityRadioButton/index.ts
src/modules/ProductDetails/VariantsSection/ColorRadioButton/ColorRadioButton.module.scss
src/modules/ProductDetails/VariantsSection/ColorRadioButton/ColorRadioButton.tsx
src/modules/ProductDetails/VariantsSection/ColorRadioButton/index.ts
src/modules/ProductDetails/VariantsSection/VariantsSection.module.scss
src/modules/ProductDetails/VariantsSection/VariantsSection.tsx

-  Add information block
- Working add to cart
- Add variants/actions block with changeable color/size functionality

[Tasks - 86bybjqj9 & 86bybjq7c]: add information block, add to cart and change color/size functionality

---

src/modules/ProductDetails/ProductDetails.tsx

-Fixed navigate to not found from product page

fixed navigate to not found from product page

---

src/context/FavouritesContext.tsx
src/main.tsx
src/modules/Favorites/Favorites.tsx
src/modules/Header/ShoppingTools/ShoppingTools.tsx
src/modules/Shared/Card/Card.tsx

- use useLocalStorage instead useState

add useLocalStorage to favoriresContext

---

src/modules/ProductDetails/ProductDetails.tsx
src/modules/ProductDetails/ProductInfo/ProductInfo.tsx
src/modules/ProductDetails/VariantsSection/VariantsSection.tsx

- Fix accessories links
- Fix key in Product Info

[Bugfix: 86byed9xa] Fix accessories links

---

src/modules/ProductDetails/VariantsSection/ColorRadioButton/ColorRadioButton.module.scss
src/modules/ProductDetails/VariantsSection/VariantsSection.tsx
src/modules/Shared/Button/Button.module.scss

- Fix empty colors
- Improve getNewLinkByVariant func
- add hover to Favorites button

[Bugfix: 86byezbn2] Fixes on Product page

---

index.html
src/helpers/scrollToTop.ts
src/index.scss
src/modules/Cart/Cart.tsx
src/modules/CatalogPage/Pagination/Pagination.tsx
src/modules/Footer/Footer.tsx
src/modules/Footer/FooterNav/FooterNav.tsx
src/modules/Header/Search/Search.module.scss
src/modules/Shared/BackLink/BackLink.module.scss
src/modules/Shared/BackLink/BackLink.tsx
src/modules/Shared/Breadcrumbs/Breadcrumbs.module.scss
src/modules/Shared/Breadcrumbs/Breadcrumbs.tsx

- add scroll on pagination
- fixed content displacement on modal open

add scroll on pagination

---

package-lock.json
src/context/FavoritesContext.tsx
src/main.tsx
src/modules/Favorites/Favorites.module.scss
src/modules/Favorites/Favorites.tsx
src/modules/Header/ShoppingTools/ShoppingTools.tsx
src/modules/ProductDetails/VariantsSection/VariantsSection.tsx
src/modules/Shared/Card/Card.tsx

[Task: 86byeywyw] add favorites page

---

package-lock.json
public/api/accessories.json
public/api/phones.json
public/api/tablets.json
src/modules/ErrorPage/ErrorPage.tsx
src/modules/ProductDetails/VariantsSection/CapacityRadioButton/CapacityRadioButton.tsx
src/modules/ProductDetails/VariantsSection/ColorRadioButton/ColorRadioButton.module.scss
src/modules/ProductDetails/VariantsSection/ColorRadioButton/ColorRadioButton.tsx
src/modules/ProductDetails/VariantsSection/VariantsSection.module.scss
src/modules/ProductDetails/VariantsSection/VariantsSection.tsx
src/modules/Shared/Button/Button.module.scss

[Task: 86byed9df] Add swiper to photos block

---

src/context/FavoritesContext.tsx

-add useReducer to FavoritesContext

add useReducer

---

src/modules/Favorites/Favorites.module.scss

##Desc
https://www.loom.com/share/9cce37ddd5f6482a8ecc3cade4f635b9?sid=6d68dc2c-5260-43e0-8364-18029fc98f79

animation added

---

package-lock.json
package.json
src/index.scss
src/modules/CatalogPage/CatalogPage.module.scss
src/modules/CatalogPage/CatalogPage.tsx
src/modules/CatalogPage/RangePriceFilter/RangePriceFilter.module.scss
src/modules/CatalogPage/RangePriceFilter/RangePriceFilter.tsx
src/vite-env.d.ts

range select added

---

src/api/products.ts
src/helpers/fetchDataFromApi.ts
src/hooks/useProductsApi.ts
src/modules/HomePage/BrandNewModelsSection/BrandNewModelsSection.tsx
src/modules/HomePage/HotPricesSection/HotPricesSection.tsx
src/modules/ProductDetails/ProductDetails.tsx

sliders logic with backend added

sliders logic with backend added

---

src/hooks/useProductsApi.ts
src/modules/Header/Search/Search.tsx

bug for search fixed

---

src/api/user.ts
src/modules/AuthScreen/AuthScreen.module.scss
src/modules/AuthScreen/AuthScreen.tsx
src/types/User.ts

logic for registration and login added

logic for registration and login added

---

package-lock.json
package.json
src/App.tsx
src/api/products.ts
src/modules/CatalogPage/CatalogPage.tsx
src/modules/ProductDetails/ProductDetails.tsx

- Added caching to pagination and product page

Add caching to pagination and product page

---

src/modules/AuthScreen/LoginForm/LoginForm.tsx
src/modules/AuthScreen/RegisterForm/RegisterForm.tsx

githab icon removed

---

README.md

added link to backend
